name: login
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.3.1
  flutter_keyboard_visibility: ^5.2.0
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  freezed_annotation: ^1.1.0
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  go_router: ^3.0.6
  google_sign_in: ^5.2.4
  reactive_forms: ^11.0.1
  provider: ^6.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  freezed: ^1.1.1

dependency_overrides:
  # I forked this package and made a pull request and its merged
  # I wait the publisher to put new version on pub.dev
  flutter_screenutil:
    git:
     url: git@github.com:Husssam12/flutter_screenutil.git


flutter:
  uses-material-design: true


  assets:
    - assets/

  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
