// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPnskQczrlksfE0IPZPgVwe5cBBQ26-4s',
    appId: '1:1017116335811:android:96c58304cd1976aef24c76',
    messagingSenderId: '1017116335811',
    projectId: 'login-87cb7',
    storageBucket: 'login-87cb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5_hvjTUoBo04EOdlMzck3DbXbH76Gp_E',
    appId: '1:1017116335811:ios:09145bf38c9d9848f24c76',
    messagingSenderId: '1017116335811',
    projectId: 'login-87cb7',
    storageBucket: 'login-87cb7.appspot.com',
    iosClientId: '1017116335811-vsee3sbba6bj97kpduf61grfoib4q95r.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
